Repository extinctsion/easyPythonpi, pull requests merged in 2023-10, with the labels that each got.

#56 Changed the library and given new look v 1.1.9 -> Testbranch
  easyPythonpi/__init__.py
  easyPythonpi/__main__.py
  easyPythonpi/__pycache__/easyPythonpi.cpython-37.pyc
  easyPythonpi/easyPythonpi.py
  easyPythonpi/methods/Graph.py
  easyPythonpi/methods/__init__.py
  easyPythonpi/methods/array.py
  easyPythonpi/methods/basics.py
  easyPythonpi/methods/linkedlist.py
  easyPythonpi/methods/matrix.py
  easyPythonpi/methods/search.py
  easyPythonpi/methods/sorting.py
  easyPythonpi/test/__init__.py
  easyPythonpi/test/__main__.py
  easyPythonpi/test/__pycache__/search.cpython-310.pyc
  easyPythonpi/test/test_Bin2Hex.py
  easyPythonpi/test/test_FibRefactored.py
  easyPythonpi/test/test_basics.py
  easyPythonpi/test/test_graph.py
  easyPythonpi/test/test_search.py
  easyPythonpi/test_cases/start_test.py
Labels: hacktoberfest-accepted, hacktoberfest2023, hacktoberfest

#58 Changed the library and given new look v 1.1.9 -> Testbranch (#56)
  easyPythonpi/__init__.py
Labels: hacktoberfest

#65 Andrew hung nguyen
  .gitignore
  easyPythonpi/methods/basics.py
  easyPythonpi/methods/bitwiseops.py
  easyPythonpi/methods/statistics.py
  easyPythonpi/methods/stringmainpulation.py
  easyPythonpi/test/test_Bin2Hex.py
  easyPythonpi/test/test_basics.py
  easyPythonpi/test/test_statistics.py
  easyPythonpi/test/test_stringmanipulation.py
Labels: hacktoberfest-accepted, hacktoberfest2023

#74 Add github workflow to run black and isort on pull request
  .github/workflows/run_black_and_isort.yml
Labels: hacktoberfest-accepted, hacktoberfest2023, hacktoberfest

#75 Andrew hung nguyen - is_palindrome() fixes and method naming convention changes
  easyPythonpi/__pycache__/easyPythonpi.cpython-311.pyc
  easyPythonpi/methods/stringmainpulation.py
  easyPythonpi/test/test_stringmanipulation.py
Labels: hacktoberfest-accepted

#70 Add workflow to run tests on pull request
  .github/workflows/run_tests.yml
Labels: hacktoberfest-accepted, hacktoberfest2023
